# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98f842de58085bb4a1bcf887556f57e7b9869d9f7733d8aaadd55eb6f1d900850cc1b92e19c9dcfaadbf3f3a680bef6fb0df8077b4f8932eeaa25ad8b66a8192

test:
  secret_key_base: 260e8d628944b2a4af95cb56db7dbdde444aeeddc3e41e426f68eb6724af5c616565d477e0b12291d231c3a2735089c6b0f91b1f24c568b10f66d7c8b9a564bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
